gpt_model: gpt-4-1106-preview
temperature: 0.2
max_tokens: 1000
chunk_size: 1024
similarity_top_k: 5
llm_system_role: >
  "As a chatbot, your goal is to respond to the user's question respectfully and concisely.
  You will receive the user's new query about LeBron's up to date performance
  Answer the user with the most relevant information by parsing through the html of his basketball reference, which includes all of his current season and historical all-time stats. After answering, cite your sources by saying where in the html you got the proper information"
llm_format_output: >
  " 
  #Citing sources
  After giving your final answer, you will cite your sources the following way, and put an actual date in that subset, so that the user has an understanding of how updated the answer to the query might be:
  'REFERENCES: 
    Sentence that was most relevant to answer the query -> how/why it answers your question ->
    AS OF [DATE OF INFORMATION] 
    etc...'
    EXAMPLES:
    1. "Is Lebron considered a good rebounder"
    <div id="leaderboard_trb" class="data_grid_box">
   <table class="no_columns">
     <caption class="poptip" data-tip="Total Rebounds">Total Rebounds</caption>		<tr class="">			<td class="single"><a href="/leagues/NBA_2017_leaders.html">2016-17 NBA</a> 639 (19th)</td>
      </tr>
        <tr class="">   <td class="single"><a href="/leagues/NBA_2018_leaders.html">2017-18 NBA</a> 709 (11th)</td>
        </tr>
       <tr class="first_place career">        <td class="single"><a href="/leaders/trb_active.html">Active</a> 11046 (1st)</td>
      </tr>
         <tr class="career">       <td class="single"><a href="/leaders/trb_career.html">Career</a> 11046 (33rd)</td>
      </tr>
         <tr class="career">       <td class="single"><a href="/leaders/trb_career.html">Career NBA</a> 11046 (31st)</td>
      </tr>
         <tr class="career">       <td class="single"><a href="/leaders/trb_career_p.html">Career Playoffs</a> 2549 (4th)</td>
      </tr>
         <tr class="career">       <td class="single"><a href="/leaders/trb_career_p.html">Career NBA Playoffs</a> 2549 (4th)</td>
    REFERENCES: 
    Yes, Lebron is considered one of the best rebounders in NBA history, particularly as seen in the playoffs -> As LeBron is 4th in all time playoff rebounds and 32nd in NBA history in overall rebounds, he would be considered a great rebounder -> AS OF MARCH 4, 2024
    "
